# Predict The Flight Ticket Price Hackathon

**Features**:

    Airline: The name of the airline.
    Date_of_Journey: The date of the journey
    Source: The source from which the service begins.
    Destination: The destination where the service ends.
    Route: The route taken by the flight to reach the destination.
    Dep_Time: The time when the journey starts from the source.
    Arrival_Time: Time of arrival at the destination.
    Duration: Total duration of the flight.
    Total_Stops: Total stops between the source and destination.
    Additional_Info: Additional information about the flight
    Price: The price of the ticket

### Import data and libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
train = pd.read_excel('Data_Train.xlsx')
test = pd.read_excel('Test_set.xlsx')

In [4]:
train.shape, test.shape

((10683, 11), (2671, 10))

In [5]:
train.info()
#test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
Airline            10683 non-null object
Date_of_Journey    10683 non-null object
Source             10683 non-null object
Destination        10683 non-null object
Route              10682 non-null object
Dep_Time           10683 non-null object
Arrival_Time       10683 non-null object
Duration           10683 non-null object
Total_Stops        10682 non-null object
Additional_Info    10683 non-null object
Price              10683 non-null int64
dtypes: int64(1), object(10)
memory usage: 918.1+ KB

In [6]:
train.head(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [7]:
for i in train.columns:
    print("Unique values in", i, train[i].nunique())

Unique values in Airline 12
Unique values in Date_of_Journey 44
Unique values in Source 5
Unique values in Destination 6
Unique values in Route 128
Unique values in Dep_Time 222
Unique values in Arrival_Time 1343
Unique values in Duration 368
Unique values in Total_Stops 5
Unique values in Additional_Info 10
Unique values in Price 1870

In [8]:
for i in test.columns:
    print("Unique values in", i, test[i].nunique())

Unique values in Airline 11
Unique values in Date_of_Journey 44
Unique values in Source 5
Unique values in Destination 6
Unique values in Route 100
Unique values in Dep_Time 199
Unique values in Arrival_Time 704
Unique values in Duration 320
Unique values in Total_Stops 5
Unique values in Additional_Info 6

### Data pre-processing

In [9]:
train_df = train[['Airline', 'Source', 'Destination', 'Total_Stops', 'Additional_Info', 'Date_of_Journey', 'Dep_Time', 
                  'Route', 'Arrival_Time', 'Price']]
test_df = test[['Airline', 'Source', 'Destination', 'Total_Stops', 'Additional_Info', 'Date_of_Journey', 'Dep_Time', 
                'Route', 'Arrival_Time']]

This is new feature __Booking_Class__ to identify the booking class i.e. **Economy, Premium Economy & Business**. For the __'Premium Economy'__ and __Business__ class its already mentioned. Rest of the airlines I have assumed as __Economy__.

In [10]:
Class = {'IndiGo': 'Economy',
         'GoAir': 'Economy',
         'Vistara': 'Economy',
         'Vistara Premium economy': 'Premium Economy',
         'Air Asia': 'Economy',
         'Trujet': 'Economy',
         'Jet Airways': 'Economy',
         'SpiceJet': 'Economy',
         'Jet Airways Business': 'Business',
         'Air India': 'Economy',
         'Multiple carriers': 'Economy',
         'Multiple carriers Premium economy': 'Premium Economy'}
train_df['Booking_Class'] = train_df['Airline'].map(Class)
test_df['Booking_Class'] = test_df['Airline'].map(Class)

This is new feature is used to indicate __Market_Share__ of each airline. This information is taken mostly from Wikipedia. For _Multiple carriers_ & _Multiple carriers Premium Economy_ I have assumed 1% & for the _Trujet_ which is new entrant in the Airline I have assumed 0.1%.

In [11]:
market = {'IndiGo': 41.3,
         'GoAir': 8.4,
         'Vistara': 3.3,
         'Vistara Premium economy': 3.3,
         'Air Asia': 3.3,
         'Trujet': 0.1,
         'Jet Airways': 17.8,
         'SpiceJet': 13.3,
         'Jet Airways Business': 17.8,
         'Air India': 13.5,
         'Multiple carriers': 1,
         'Multiple carriers Premium economy': 1}
train_df['Market_Share'] = train_df['Airline'].map(market)
test_df['Market_Share'] = test_df['Airline'].map(market)

One of the very important factors which influences Flight Ticket price is how soon you book the ticket. Since this information was not provided in the dataset I have assumed 01-Mar-2019 as ticket booking date and created new feature __Days_to_Departure__

In [12]:
df1 = train_df.copy() 
df1['Day_of_Booking'] = '1/3/2019'
df1['Day_of_Booking'] = pd.to_datetime(df1['Day_of_Booking'],format='%d/%m/%Y')
df1['Date_of_Journey'] = pd.to_datetime(df1['Date_of_Journey'],format='%d/%m/%Y')
df1['Days_to_Departure'] = (df1['Date_of_Journey'] - df1['Day_of_Booking']).dt.days
train_df['Days_to_Departure'] = df1['Days_to_Departure']

df2 = test_df.copy() 
df2['Day_of_Booking'] = '1/3/2019'
df2['Day_of_Booking'] = pd.to_datetime(df2['Day_of_Booking'],format='%d/%m/%Y')
df2['Date_of_Journey'] = pd.to_datetime(df2['Date_of_Journey'],format='%d/%m/%Y')
df2['Days_to_Departure'] = (df2['Date_of_Journey'] - df2['Day_of_Booking']).dt.days
test_df['Days_to_Departure'] = df2['Days_to_Departure']

del df1, df2

In [13]:
train_df.head(2)

,Airline,Source,Destination,Total_Stops,Additional_Info,Date_of_Journey,Dep_Time,Route,Arrival_Time,Price,Booking_Class,Market_Share,Days_to_Departure
0,IndiGo,Banglore,New Delhi,non-stop,No info,24/03/2019,22:20,BLR → DEL,01:10 22 Mar,3897,Economy,41.3,23
1,Air India,Kolkata,Banglore,2 stops,No info,1/05/2019,05:50,CCU → IXR → BBI → BLR,13:15,7662,Economy,13.5,61

In [14]:
# Let's take only Arrial Time (withut including date)
train_df['Arrival_Time'] = train['Arrival_Time'].str.split(' ').str[0]
test_df['Arrival_Time'] = test['Arrival_Time'].str.split(' ').str[0]

Another important parameter which influences Flight Price is Departure time of the flight i.e. Morning, Noon, Evening or Night. So created this new feature __Dep_timeofday__ which indicate Departure Time of the day. Also applied same concept to Arrival Time and created another feature __Arr_timeofday__

In [15]:
def get_departure(dep):
    dep = dep.split(':')
    dep = int(dep[0])
    if (dep >= 6 and dep < 12):
        return 'Morning'
    elif (dep >= 12 and dep < 17):
        return 'Noon'
    elif (dep >= 17 and dep < 20):
        return 'Evening'
    else:
        return 'Night'
    
train_df['Dep_timeofday'] = train['Dep_Time'].apply(get_departure)   
test_df['Dep_timeofday'] = test['Dep_Time'].apply(get_departure) 

train_df['Arr_timeofday'] = train['Arrival_Time'].apply(get_departure)   
test_df['Arr_timeofday'] = test['Arrival_Time'].apply(get_departure)

Converted __Total_Stops__ categorical column into numeric

In [16]:
train_df['Total_Stops'] = train_df['Total_Stops'].str.replace('non-stop','0')
train_df['Total_Stops'] = train_df['Total_Stops'].str.replace('stops','')
train_df['Total_Stops'] = train_df['Total_Stops'].str.replace('stop','')
train_df['Total_Stops'].fillna(0, inplace=True)   
train_df['Total_Stops'] = train_df['Total_Stops'].astype(float)

test_df['Total_Stops'] = test_df['Total_Stops'].str.replace('non-stop','0')
test_df['Total_Stops'] = test_df['Total_Stops'].str.replace('stops','')
test_df['Total_Stops'] = test_df['Total_Stops'].str.replace('stop','')
#test_df['Total_Stops'].fillna(0, inplace=True)
test_df['Total_Stops'] = test_df['Total_Stops'].astype(float)

Converted __Duration__ column into minutes

In [17]:
train_df['Hours'] = train['Duration'].str.split(' ').str[0]
train_df['Hours'] = train_df['Hours'].str.replace('h','').astype(float)
train_df['Hours'].fillna(0, inplace=True) 

train_df['Minutes'] = train['Duration'].str.split(' ').str[1]
train_df['Minutes'] = train_df['Minutes'].str.replace('m','').astype(float)
train_df['Minutes'].fillna(0, inplace=True)

test_df['Hours'] = test['Duration'].str.split(' ').str[0]
test_df['Hours'] = test_df['Hours'].str.replace('h','').astype(float)
test_df['Hours'].fillna(0, inplace=True) 

test_df['Minutes'] = test['Duration'].str.split(' ').str[1]
test_df['Minutes'] = test_df['Minutes'].str.replace('m','').astype(float)
test_df['Minutes'].fillna(0, inplace=True)

train_df['Hours'] = train_df['Hours'] * 60
train_df['Duration'] = train_df['Hours'] + train_df['Minutes']

test_df['Hours'] = test_df['Hours'] * 60
test_df['Duration'] = test_df['Hours'] + test_df['Minutes']

train_df.drop(['Hours', 'Minutes'], axis=1, inplace=True)
test_df.drop(['Hours', 'Minutes'], axis=1, inplace=True)

In [18]:
train_df.head(2)

,Airline,Source,Destination,Total_Stops,Additional_Info,Date_of_Journey,Dep_Time,Route,Arrival_Time,Price,Booking_Class,Market_Share,Days_to_Departure,Dep_timeofday,Arr_timeofday,Duration
0,IndiGo,Banglore,New Delhi,0.0,No info,24/03/2019,22:20,BLR → DEL,01:10,3897,Economy,41.3,23,Night,Night,170.0
1,Air India,Kolkata,Banglore,2.0,No info,1/05/2019,05:50,CCU → IXR → BBI → BLR,13:15,7662,Economy,13.5,61,Night,Noon,445.0

Let's take logarithmic values of __Price__ and __Duration__

In [19]:
train_df['Price'] = np.log1p(train_df['Price'])

train_df['Duration'] = np.log1p(train_df['Duration'])
test_df['Duration'] = np.log1p(test_df['Duration'])

In [20]:
train_df['Additional_Info'] = train_df['Additional_Info'].str.replace('No info', 'No Info')
test_df['Additional_Info'] = test_df['Additional_Info'].str.replace('No info', 'No Info')

Therea are lot of categorical variable. Used pandas __get_dummies__ to deal with all the categorical variables

In [21]:
train_df = pd.get_dummies(train_df, columns=['Airline', 'Source', 'Destination', 'Additional_Info', 'Date_of_Journey',
                                             'Dep_Time', 'Arrival_Time', 'Dep_timeofday', 'Booking_Class', 'Arr_timeofday'],
                          drop_first=True)
test_df = pd.get_dummies(test_df, columns=['Airline', 'Source', 'Destination', 'Additional_Info', 'Date_of_Journey',
                                           'Dep_Time', 'Arrival_Time', 'Dep_timeofday', 'Booking_Class', 'Arr_timeofday'],
                         drop_first=True)

For the __Route__ column, I have applied TF-IDF text extraction to create one column for each value of location. There are 43 unique location so 43 new feature created out of __Route__ column. The results are stored in dataframe.

In [22]:
def clean_route(route):
    route = str(route)
    route = route.split(' → ')
    return ' '.join(route)

train_df['Route'] = train_df['Route'].apply(clean_route)
test_df['Route'] = test_df['Route'].apply(clean_route)

from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(ngram_range=(1, 1), lowercase=False)
train_route = tf.fit_transform(train_df['Route'])
test_route = tf.transform(test_df['Route'])

train_route = pd.DataFrame(data=train_route.toarray(), columns=tf.get_feature_names())
test_route = pd.DataFrame(data=test_route.toarray(), columns=tf.get_feature_names())

In [23]:
train_route.head(5)
#test_route.head(5)

,AMD,ATQ,BBI,BDQ,BHO,BLR,BOM,CCU,COK,DED,...,PAT,PNQ,RPR,STV,TRV,UDR,VGA,VNS,VTZ,nan
0,0.0,0.0,0.000000,0.0,0.0,0.783012,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.619874,0.0,0.0,0.194833,0.000000,0.248235,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.0,0.0,0.000000,0.241494,0.000000,0.271844,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.0,0.0,0.274089,0.000000,0.349214,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.0,0.0,0.284914,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Now, let's concatenate __train_route__ and __test_route__ dataframes with corresponding __train_df__ and __test_df__ dataframe which will be used further for modelling

In [24]:
train_df = pd.concat([train_df, train_route], axis=1) 
train_df.drop('Route', axis=1, inplace=True)

test_df = pd.concat([test_df, test_route], axis=1) 
test_df.drop('Route', axis=1, inplace=True)

In [25]:
train_df.head()
#test_df.head()

,Total_Stops,Price,Market_Share,Days_to_Departure,Duration,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,...,PAT,PNQ,RPR,STV,TRV,UDR,VGA,VNS,VTZ,nan
0,0.0,8.268219,41.3,23,5.141664,0,0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,8.944159,13.5,61,6.100319,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.0,9.538420,17.8,100,7.039660,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,8.735364,41.3,72,5.786897,0,0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,9.495745,41.3,0,5.655992,0,0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Train test split

In [187]:
X = train_df.drop(labels=['Price'], axis=1)
y = train_df['Price'].values

from sklearn.model_selection import train_test_split
X_train, X_cv, y_train, y_cv = train_test_split(X, y, test_size=0.25, random_state=1)

In [188]:
X_train.shape, y_train.shape, X_cv.shape, y_cv.shape

((8012, 569), (8012,), (2671, 569), (2671,))

### Build the model

In [189]:
from math import sqrt 
from sklearn.metrics import mean_squared_log_error

In [190]:
import lightgbm as lgb
train_data = lgb.Dataset(X_train, label=y_train)
test_data = lgb.Dataset(X_cv, label=y_cv)

param = {'objective': 'regression',
         'boosting': 'gbdt',
         'num_iterations': 3000,   
         'learning_rate': 0.06,  
         'num_leaves': 40,  
         'max_depth': 24,   
         'min_data_in_leaf':11,  
         'max_bin': 4, 
         'metric': 'l2_root'
         }

lgbm = lgb.train(params=param,
                 verbose_eval=1000,
                 train_set=train_data,
                 valid_sets=[test_data])

y_pred2 = lgbm.predict(X_cv)
print('RMSLE:', sqrt(mean_squared_log_error(np.exp(y_cv), np.exp(y_pred2))))

[1000]	valid_0's rmse: 0.107172
[2000]	valid_0's rmse: 0.105563
[3000]	valid_0's rmse: 0.105689
RMSLE: 0.10567509598337499

In [191]:
from xgboost import XGBRegressor
xgb = XGBRegressor(max_depth=9, 
                   learning_rate=0.5, 
                   n_estimators=112, 
                   silent=False, 
                   objective='reg:linear', 
                   booster='gbtree', 
                   n_jobs=1, 
                   nthread=None, 
                   gamma=0, 
                   min_child_weight=1, 
                   max_delta_step=0, 
                   subsample=1, 
                   colsample_bytree=1, 
                   colsample_bylevel=1, 
                   reg_alpha=1, 
                   reg_lambda=1, 
                   scale_pos_weight=1, 
                   base_score=0.5, 
                   random_state=0, 
                   seed=None)
xgb.fit(X_train, y_train)
y_pred1 = xgb.predict(X_cv)
print('RMSLE:', sqrt(mean_squared_log_error(np.exp(y_cv), np.exp(y_pred1))))
#RMSLE:0.11124007381703037

RMSLE: 0.11125264058400451

In [192]:
from sklearn.ensemble import BaggingRegressor
br = BaggingRegressor(base_estimator=None, 
                      n_estimators=50, 
                      max_samples=1.0, 
                      max_features=1.0, 
                      bootstrap=True, 
                      bootstrap_features=False, 
                      oob_score=False, 
                      warm_start=False, 
                      n_jobs=1, 
                      random_state=1, 
                      verbose=0)
br.fit(X_train, y_train)
y_pred3 = br.predict(X_cv)
print('RMSLE:', sqrt(mean_squared_log_error(np.exp(y_cv), np.exp(y_pred3))))
#RMSLE:0.11265336177662688

RMSLE: 0.11278238526307509

In [193]:
from sklearn.ensemble import GradientBoostingRegressor
gb = GradientBoostingRegressor(loss='ls', 
                               learning_rate=0.3, 
                               n_estimators=380, 
                               subsample=1.0, 
                               criterion='friedman_mse', 
                               min_samples_split=30, 
                               min_samples_leaf=1, 
                               min_weight_fraction_leaf=0.0, 
                               max_depth=7, 
                               min_impurity_decrease=0.0, 
                               min_impurity_split=None, 
                               init=None, 
                               random_state=0, 
                               max_features=None, 
                               alpha=0.9, 
                               verbose=100, 
                               max_leaf_nodes=None, 
                               warm_start=False, 
                               presort='auto')
gb.fit(X_train, y_train)
y_pred4 = gb.predict(X_cv)
print('RMSLE:', sqrt(mean_squared_log_error(np.exp(y_cv), np.exp(y_pred4))))
#RMSLE:0.11014737617371691

      Iter       Train Loss   Remaining Time
         1           0.1420            4.18m
         2           0.0829            3.82m
         3           0.0515            4.03m
         4           0.0356            3.96m
         5           0.0270            3.91m
         6           0.0225            4.00m
         7           0.0195            3.92m
         8           0.0177            3.85m
         9           0.0163            3.81m
        10           0.0155            3.73m
        11           0.0146            3.63m
        12           0.0141            3.49m
        13           0.0137            3.37m
        14           0.0133            3.28m
        15           0.0129            3.18m
        16           0.0127            3.08m
        17           0.0125            2.98m
        18           0.0124            2.87m
        19           0.0122            2.77m
        20           0.0117            2.81m
        21           0.0116            2.76m
        22           0.0112            2.77m
        23           0.0111            2.71m
        24           0.0111            2.65m
        25           0.0110            2.60m
        26           0.0109            2.55m
        27           0.0107            2.51m
        28           0.0106            2.47m
        29           0.0105            2.46m
        30           0.0104            2.44m
        31           0.0103            2.41m
        32           0.0103            2.36m
        33           0.0100            2.34m
        34           0.0100            2.31m
        35           0.0099            2.30m
        36           0.0097            2.29m
        37           0.0097            2.25m
        38           0.0096            2.22m
        39           0.0096            2.20m
        40           0.0095            2.17m
        41           0.0094            2.15m
        42           0.0093            2.13m
        43           0.0093            2.12m
        44           0.0092            2.10m
        45           0.0092            2.08m
        46           0.0091            2.05m
        47           0.0090            2.04m
        48           0.0090            2.02m
        49           0.0089            2.02m
        50           0.0089            2.00m
        51           0.0088            1.98m
        52           0.0087            1.96m
        53           0.0086            1.95m
        54           0.0085            1.95m
        55           0.0084            1.94m
        56           0.0083            1.92m
        57           0.0082            1.90m
        58           0.0082            1.88m
        59           0.0081            1.86m
        60           0.0081            1.84m
        61           0.0081            1.83m
        62           0.0080            1.82m
        63           0.0080            1.80m
        64           0.0080            1.79m
        65           0.0079            1.79m
        66           0.0079            1.78m
        67           0.0078            1.77m
        68           0.0078            1.76m
        69           0.0078            1.74m
        70           0.0078            1.73m
        71           0.0077            1.71m
        72           0.0077            1.70m
        73           0.0077            1.69m
        74           0.0077            1.67m
        75           0.0077            1.66m
        76           0.0075            1.67m
        77           0.0075            1.66m
        78           0.0075            1.65m
        79           0.0074            1.65m
        80           0.0073            1.64m
        81           0.0073            1.63m
        82           0.0072            1.63m
        83           0.0072            1.62m
        84           0.0072            1.61m
        85           0.0071            1.60m
        86           0.0071            1.59m
        87           0.0071            1.58m
        88           0.0071            1.57m
        89           0.0071            1.56m
        90           0.0071            1.55m
        91           0.0070            1.54m
        92           0.0070            1.53m
        93           0.0070            1.53m
        94           0.0069            1.53m
        95           0.0069            1.52m
        96           0.0068            1.51m
        97           0.0068            1.51m
        98           0.0068            1.50m
        99           0.0068            1.49m
       100           0.0067            1.48m
       101           0.0067            1.47m
       102           0.0067            1.46m
       103           0.0067            1.45m
       104           0.0066            1.45m
       105           0.0066            1.44m
       106           0.0066            1.43m
       107           0.0065            1.42m
       108           0.0065            1.43m
       109           0.0065            1.42m
       110           0.0064            1.42m
       111           0.0064            1.41m
       112           0.0064            1.40m
       113           0.0064            1.39m
       114           0.0064            1.38m
       115           0.0063            1.38m
       116           0.0063            1.37m
       117           0.0063            1.36m
       118           0.0063            1.36m
       119           0.0063            1.35m
       120           0.0063            1.35m
       121           0.0063            1.34m
       122           0.0062            1.33m
       123           0.0062            1.33m
       124           0.0062            1.33m
       125           0.0062            1.32m
       126           0.0062            1.31m
       127           0.0062            1.31m
       128           0.0061            1.30m
       129           0.0061            1.29m
       130           0.0061            1.28m
       131           0.0061            1.28m
       132           0.0061            1.27m
       133           0.0061            1.26m
       134           0.0060            1.25m
       135           0.0060            1.25m
       136           0.0060            1.24m
       137           0.0059            1.23m
       138           0.0058            1.23m
       139           0.0058            1.22m
       140           0.0058            1.21m
       141           0.0058            1.20m
       142           0.0058            1.20m
       143           0.0058            1.19m
       144           0.0057            1.19m
       145           0.0057            1.18m
       146           0.0057            1.18m
       147           0.0057            1.17m
       148           0.0056            1.17m
       149           0.0056            1.16m
       150           0.0056            1.15m
       151           0.0056            1.15m
       152           0.0056            1.14m
       153           0.0055            1.13m
       154           0.0055            1.13m
       155           0.0055            1.12m
       156           0.0055            1.11m
       157           0.0055            1.11m
       158           0.0055            1.10m
       159           0.0055            1.10m
       160           0.0055            1.09m
       161           0.0055            1.09m
       162           0.0054            1.08m
       163           0.0054            1.07m
       164           0.0054            1.07m
       165           0.0054            1.06m
       166           0.0054            1.05m
       167           0.0054            1.05m
       168           0.0054            1.04m
       169           0.0054            1.04m
       170           0.0053            1.04m
       171           0.0053            1.03m
       172           0.0053            1.02m
       173           0.0053            1.02m
       174           0.0053            1.01m
       175           0.0052            1.01m
       176           0.0052            1.00m
       177           0.0052           59.80s
       178           0.0052           59.50s
       179           0.0052           59.34s
       180           0.0052           59.05s
       181           0.0052           58.87s
       182           0.0052           58.57s

       183           0.0052           58.23s
       184           0.0051           57.90s
       185           0.0051           57.57s
       186           0.0051           57.23s
       187           0.0051           56.85s
       188           0.0051           56.47s
       189           0.0051           56.10s
       190           0.0051           55.77s
       191           0.0051           55.53s
       192           0.0050           55.20s
       193           0.0050           55.06s
       194           0.0050           54.89s
       195           0.0050           54.57s
       196           0.0050           54.18s
       197           0.0050           53.80s
       198           0.0049           53.53s
       199           0.0049           53.21s
       200           0.0049           52.91s
       201           0.0049           52.66s
       202           0.0049           52.58s
       203           0.0049           52.21s
       204           0.0049           51.83s
       205           0.0048           51.49s
       206           0.0048           51.40s
       207           0.0048           51.17s
       208           0.0047           51.10s
       209           0.0047           50.98s
       210           0.0047           50.66s
       211           0.0047           50.52s
       212           0.0046           50.16s
       213           0.0046           49.76s
       214           0.0046           49.38s
       215           0.0046           49.17s
       216           0.0046           48.98s
       217           0.0046           48.62s
       218           0.0046           48.27s
       219           0.0046           47.93s
       220           0.0046           47.55s
       221           0.0045           47.24s
       222           0.0045           46.94s
       223           0.0045           46.61s
       224           0.0045           46.27s
       225           0.0045           45.96s
       226           0.0045           45.70s
       227           0.0045           45.59s
       228           0.0044           45.34s
       229           0.0044           45.01s
       230           0.0044           44.73s
       231           0.0044           44.45s
       232           0.0044           44.13s
       233           0.0044           43.84s
       234           0.0044           43.48s
       235           0.0044           43.20s
       236           0.0044           42.96s
       237           0.0044           42.64s
       238           0.0043           42.29s
       239           0.0043           41.92s
       240           0.0043           41.58s
       241           0.0043           41.23s
       242           0.0043           40.92s
       243           0.0043           40.59s
       244           0.0043           40.28s
       245           0.0043           39.95s
       246           0.0043           39.65s
       247           0.0043           39.32s
       248           0.0043           39.02s
       249           0.0043           38.72s
       250           0.0043           38.40s
       251           0.0042           38.10s
       252           0.0042           37.82s
       253           0.0042           37.53s
       254           0.0042           37.19s
       255           0.0042           36.89s
       256           0.0042           36.61s
       257           0.0042           36.37s
       258           0.0042           36.04s
       259           0.0042           35.70s
       260           0.0042           35.40s
       261           0.0042           35.14s
       262           0.0041           34.93s
       263           0.0041           34.63s
       264           0.0041           34.42s
       265           0.0041           34.09s
       266           0.0041           33.84s
       267           0.0040           33.63s
       268           0.0040           33.36s
       269           0.0040           33.14s
       270           0.0040           32.80s
       271           0.0040           32.48s
       272           0.0039           32.22s
       273           0.0039           32.01s
       274           0.0039           31.74s
       275           0.0039           31.45s
       276           0.0039           31.13s
       277           0.0039           30.81s
       278           0.0039           30.49s
       279           0.0039           30.20s
       280           0.0039           29.90s
       281           0.0039           29.60s
       282           0.0039           29.30s
       283           0.0038           29.10s
       284           0.0038           28.87s
       285           0.0038           28.55s
       286           0.0038           28.24s
       287           0.0038           27.95s
       288           0.0037           27.64s
       289           0.0037           27.32s
       290           0.0037           27.01s
       291           0.0037           26.78s
       292           0.0037           26.45s
       293           0.0037           26.13s
       294           0.0037           25.83s
       295           0.0037           25.50s
       296           0.0037           25.21s
       297           0.0037           24.91s
       298           0.0037           24.60s
       299           0.0037           24.38s
       300           0.0037           24.08s
       301           0.0036           23.77s
       302           0.0036           23.47s
       303           0.0036           23.17s
       304           0.0036           22.89s
       305           0.0036           22.62s
       306           0.0036           22.40s
       307           0.0035           22.09s
       308           0.0035           21.77s
       309           0.0035           21.45s
       310           0.0035           21.17s
       311           0.0035           20.96s
       312           0.0035           20.64s
       313           0.0035           20.32s
       314           0.0034           20.03s
       315           0.0034           19.74s
       316           0.0034           19.43s
       317           0.0034           19.19s
       318           0.0034           18.89s
       319           0.0034           18.60s
       320           0.0034           18.29s
       321           0.0034           17.99s
       322           0.0034           17.68s
       323           0.0034           17.37s
       324           0.0034           17.07s
       325           0.0034           16.76s
       326           0.0034           16.46s
       327           0.0034           16.15s
       328           0.0033           15.83s
       329           0.0033           15.51s
       330           0.0033           15.20s
       331           0.0033           14.91s
       332           0.0033           14.60s
       333           0.0033           14.28s
       334           0.0033           13.99s
       335           0.0033           13.68s
       336           0.0033           13.39s
       337           0.0033           13.08s
       338           0.0033           12.77s
       339           0.0033           12.46s
       340           0.0033           12.15s
       341           0.0033           11.83s
       342           0.0033           11.52s
       343           0.0033           11.22s
       344           0.0033           10.90s
       345           0.0033           10.60s
       346           0.0033           10.29s
       347           0.0033            9.98s
       348           0.0033            9.68s
       349           0.0032            9.37s
       350           0.0032            9.08s
       351           0.0032            8.77s
       352           0.0032            8.46s
       353           0.0032            8.16s
       354           0.0032            7.86s
       355           0.0032            7.55s
       356           0.0032            7.25s
       357           0.0032            6.94s
       358           0.0032            6.65s
       359           0.0032            6.34s
       360           0.0032            6.04s
       361           0.0032            5.74s
       362           0.0032            5.43s
       363           0.0032            5.13s
       364           0.0032            4.83s
       365           0.0032            4.53s

       366           0.0032            4.24s
       367           0.0032            3.94s
       368           0.0031            3.64s
       369           0.0031            3.34s
       370           0.0031            3.03s
       371           0.0031            2.73s
       372           0.0031            2.43s
       373           0.0031            2.12s
       374           0.0031            1.82s
       375           0.0031            1.52s
       376           0.0031            1.21s
       377           0.0031            0.91s
       378           0.0031            0.61s
       379           0.0031            0.30s
       380           0.0031            0.00s
RMSLE: 0.10977714681935279

In [194]:
y_pred = y_pred1*0.10 + y_pred2*0.50 + y_pred3*0.20 + y_pred4*0.20
print('RMSLE:', sqrt(mean_squared_log_error(np.exp(y_cv), np.exp(y_pred))))

RMSLE: 0.1013472363709534

## Predict on test set

In [195]:
train_df['Dep_Time_22:30'] = 0

In [196]:
missing_cols_test = []
for col in train_df.columns:
    if col not in test_df.columns:
        missing_cols_test.append(col)
        
for i in missing_cols_test:
    test_df[i] = 0

test_df.drop('Price', axis=1, inplace=True)

In [197]:
train_df = train_df.reindex(sorted(train_df.columns), axis=1)
test_df = test_df.reindex(sorted(test_df.columns), axis=1)

In [198]:
train_df.shape, test_df.shape

((10683, 571), (2671, 570))

In [199]:
X_train = train_df.drop(labels='Price', axis=1)
y_train = train_df['Price'].values

X_test = test_df

In [200]:
X_train.shape, X_test.shape

((10683, 570), (2671, 570))

In [201]:
from xgboost import XGBRegressor
xgb = XGBRegressor(max_depth=9, 
                   learning_rate=0.5, 
                   n_estimators=112, 
                   silent=False, 
                   objective='reg:linear', 
                   booster='gbtree', 
                   n_jobs=1, 
                   nthread=None, 
                   gamma=0, 
                   min_child_weight=1, 
                   max_delta_step=0, 
                   subsample=1, 
                   colsample_bytree=1, 
                   colsample_bylevel=1, 
                   reg_alpha=0.89, 
                   reg_lambda=1, 
                   scale_pos_weight=1, 
                   base_score=0.5, 
                   random_state=0, 
                   seed=None)
xgb.fit(X_train, y_train)
y_pred1 = xgb.predict(X_test)

In [202]:
import lightgbm as lgb
train_data = lgb.Dataset(X_train, label=y_train)

param = {'objective': 'regression',
         'boosting': 'gbdt',
         'num_iterations': 3000,   
         'learning_rate': 0.06,  
         'num_leaves': 40,  
         'max_depth': 24,   
         'min_data_in_leaf':11,  
         'max_bin': 4, 
         'metric': 'l2_root'
         }

lgbm = lgb.train(params=param,
                 train_set=train_data)

y_pred2 = lgbm.predict(X_test)

In [203]:
from sklearn.ensemble import BaggingRegressor
br = BaggingRegressor(base_estimator=None, 
                      n_estimators=50, 
                      max_samples=1.0, 
                      max_features=1.0, 
                      bootstrap=True, 
                      bootstrap_features=False, 
                      oob_score=False, 
                      warm_start=False, 
                      n_jobs=1, 
                      random_state=1, 
                      verbose=0)
br.fit(X_train, y_train)
y_pred3 = br.predict(X_test)

In [204]:
from sklearn.ensemble import GradientBoostingRegressor
gb = GradientBoostingRegressor(loss='ls', 
                               learning_rate=0.3, 
                               n_estimators=380, 
                               subsample=1.0, 
                               criterion='friedman_mse', 
                               min_samples_split=30, 
                               min_samples_leaf=1, 
                               min_weight_fraction_leaf=0.0, 
                               max_depth=7, 
                               min_impurity_decrease=0.0, 
                               min_impurity_split=None, 
                               init=None, 
                               random_state=0, 
                               max_features=None, 
                               alpha=0.9, 
                               verbose=100, 
                               max_leaf_nodes=None, 
                               warm_start=False, 
                               presort='auto')
gb.fit(X_train, y_train)
y_pred4 = gb.predict(X_test)

      Iter       Train Loss   Remaining Time
         1           0.1429            4.23m
         2           0.0829            4.17m
         3           0.0526            4.09m
         4           0.0367            4.03m
         5           0.0281            3.99m
         6           0.0228            3.95m
         7           0.0199            3.97m
         8           0.0178            3.89m
         9           0.0167            3.92m
        10           0.0159            3.86m
        11           0.0153            3.79m
        12           0.0145            3.74m
        13           0.0140            3.69m
        14           0.0137            3.60m
        15           0.0133            3.52m
        16           0.0131            3.44m
        17           0.0128            3.43m
        18           0.0127            3.36m
        19           0.0126            3.31m
        20           0.0124            3.33m
        21           0.0122            3.34m
        22           0.0121            3.29m
        23           0.0120            3.24m
        24           0.0117            3.21m
        25           0.0116            3.22m
        26           0.0114            3.19m
        27           0.0113            3.16m
        28           0.0111            3.17m
        29           0.0111            3.12m
        30           0.0110            3.06m
        31           0.0109            3.00m
        32           0.0109            2.96m
        33           0.0108            2.95m
        34           0.0107            2.91m
        35           0.0107            2.87m
        36           0.0105            2.88m
        37           0.0104            2.86m
        38           0.0103            2.83m
        39           0.0101            2.87m
        40           0.0100            2.85m
        41           0.0100            2.85m
        42           0.0099            2.83m
        43           0.0097            2.84m
        44           0.0096            2.82m
        45           0.0096            2.80m
        46           0.0095            2.78m
        47           0.0094            2.76m
        48           0.0094            2.76m
        49           0.0093            2.74m
        50           0.0093            2.71m
        51           0.0091            2.69m
        52           0.0091            2.66m
        53           0.0089            2.66m
        54           0.0089            2.63m
        55           0.0089            2.60m
        56           0.0088            2.59m
        57           0.0088            2.55m
        58           0.0087            2.52m
        59           0.0086            2.50m
        60           0.0086            2.47m
        61           0.0085            2.46m
        62           0.0085            2.43m
        63           0.0084            2.41m
        64           0.0084            2.39m
        65           0.0084            2.37m
        66           0.0083            2.35m
        67           0.0083            2.33m
        68           0.0083            2.32m
        69           0.0082            2.30m
        70           0.0082            2.28m
        71           0.0082            2.26m
        72           0.0082            2.25m
        73           0.0081            2.23m
        74           0.0081            2.21m
        75           0.0081            2.20m
        76           0.0080            2.18m
        77           0.0080            2.17m
        78           0.0080            2.16m
        79           0.0080            2.14m
        80           0.0079            2.12m
        81           0.0077            2.13m
        82           0.0076            2.14m
        83           0.0075            2.15m
        84           0.0075            2.14m
        85           0.0074            2.12m
        86           0.0074            2.11m
        87           0.0074            2.10m
        88           0.0073            2.09m
        89           0.0073            2.08m
        90           0.0073            2.06m
        91           0.0073            2.05m
        92           0.0072            2.05m
        93           0.0072            2.05m
        94           0.0072            2.04m
        95           0.0071            2.04m
        96           0.0070            2.02m
        97           0.0070            2.01m
        98           0.0070            2.00m
        99           0.0070            2.00m
       100           0.0069            1.99m
       101           0.0069            1.98m
       102           0.0069            1.97m
       103           0.0069            1.96m
       104           0.0069            1.95m
       105           0.0068            1.95m
       106           0.0068            1.94m
       107           0.0067            1.94m
       108           0.0067            1.96m
       109           0.0066            1.95m
       110           0.0066            1.94m
       111           0.0066            1.93m
       112           0.0066            1.91m
       113           0.0065            1.90m
       114           0.0065            1.89m
       115           0.0065            1.88m
       116           0.0065            1.87m
       117           0.0065            1.86m
       118           0.0065            1.85m
       119           0.0065            1.85m
       120           0.0064            1.84m
       121           0.0064            1.83m
       122           0.0064            1.82m
       123           0.0064            1.81m
       124           0.0064            1.81m
       125           0.0063            1.80m
       126           0.0063            1.79m
       127           0.0063            1.78m
       128           0.0063            1.78m
       129           0.0063            1.77m
       130           0.0063            1.76m
       131           0.0063            1.75m
       132           0.0063            1.75m
       133           0.0062            1.74m
       134           0.0062            1.74m
       135           0.0062            1.72m
       136           0.0061            1.71m
       137           0.0061            1.70m
       138           0.0061            1.69m
       139           0.0061            1.69m
       140           0.0060            1.68m
       141           0.0060            1.68m
       142           0.0060            1.67m
       143           0.0060            1.68m
       144           0.0059            1.67m
       145           0.0059            1.67m
       146           0.0059            1.66m
       147           0.0059            1.65m
       148           0.0059            1.65m
       149           0.0059            1.64m
       150           0.0058            1.63m
       151           0.0058            1.62m
       152           0.0058            1.61m
       153           0.0058            1.60m
       154           0.0058            1.59m
       155           0.0058            1.58m
       156           0.0058            1.57m
       157           0.0058            1.56m
       158           0.0058            1.55m
       159           0.0058            1.54m
       160           0.0058            1.53m
       161           0.0058            1.53m
       162           0.0058            1.52m
       163           0.0057            1.51m
       164           0.0057            1.51m
       165           0.0057            1.50m
       166           0.0057            1.50m
       167           0.0056            1.49m
       168           0.0056            1.48m
       169           0.0056            1.48m
       170           0.0056            1.47m
       171           0.0056            1.46m
       172           0.0056            1.45m
       173           0.0056            1.45m
       174           0.0056            1.44m
       175           0.0056            1.43m
       176           0.0056            1.43m
       177           0.0055            1.42m
       178           0.0055            1.41m
       179           0.0055            1.41m
       180           0.0055            1.40m
       181           0.0055            1.39m
       182           0.0054            1.38m

       183           0.0054            1.37m
       184           0.0054            1.37m
       185           0.0054            1.36m
       186           0.0053            1.36m
       187           0.0053            1.35m
       188           0.0052            1.34m
       189           0.0052            1.34m
       190           0.0052            1.33m
       191           0.0051            1.32m
       192           0.0051            1.31m
       193           0.0051            1.31m
       194           0.0051            1.30m
       195           0.0051            1.29m
       196           0.0051            1.29m
       197           0.0051            1.28m
       198           0.0050            1.27m
       199           0.0050            1.26m
       200           0.0050            1.25m
       201           0.0050            1.25m
       202           0.0050            1.24m
       203           0.0050            1.23m
       204           0.0050            1.22m
       205           0.0049            1.22m
       206           0.0049            1.21m
       207           0.0049            1.20m
       208           0.0049            1.20m
       209           0.0049            1.19m
       210           0.0049            1.18m
       211           0.0048            1.17m
       212           0.0048            1.16m
       213           0.0048            1.15m
       214           0.0048            1.15m
       215           0.0048            1.14m
       216           0.0048            1.13m
       217           0.0048            1.13m
       218           0.0048            1.12m
       219           0.0048            1.12m
       220           0.0048            1.11m
       221           0.0047            1.11m
       222           0.0047            1.10m
       223           0.0047            1.10m
       224           0.0046            1.09m
       225           0.0046            1.09m
       226           0.0046            1.08m
       227           0.0046            1.07m
       228           0.0045            1.06m
       229           0.0045            1.06m
       230           0.0045            1.05m
       231           0.0045            1.05m
       232           0.0045            1.04m
       233           0.0045            1.03m
       234           0.0044            1.03m
       235           0.0044            1.02m
       236           0.0044            1.01m
       237           0.0044            1.01m
       238           0.0044           59.83s
       239           0.0044           59.34s
       240           0.0044           58.95s
       241           0.0044           58.63s
       242           0.0044           58.22s
       243           0.0044           57.73s
       244           0.0044           57.34s
       245           0.0043           56.99s
       246           0.0043           56.53s
       247           0.0043           56.08s
       248           0.0043           55.71s
       249           0.0043           55.29s
       250           0.0043           54.80s
       251           0.0043           54.37s
       252           0.0043           53.88s
       253           0.0043           53.55s
       254           0.0042           53.17s
       255           0.0042           52.73s
       256           0.0042           52.27s
       257           0.0042           51.91s
       258           0.0042           51.67s
       259           0.0042           51.21s
       260           0.0041           50.88s
       261           0.0041           50.39s
       262           0.0041           49.95s
       263           0.0041           49.47s
       264           0.0041           49.14s
       265           0.0041           48.67s
       266           0.0041           48.27s
       267           0.0041           47.85s
       268           0.0041           47.53s
       269           0.0041           47.10s
       270           0.0041           46.66s
       271           0.0041           46.19s
       272           0.0041           45.80s
       273           0.0040           45.47s
       274           0.0040           45.07s
       275           0.0040           44.73s
       276           0.0040           44.32s
       277           0.0040           43.88s
       278           0.0040           43.43s
       279           0.0040           43.00s
       280           0.0040           42.55s
       281           0.0040           42.16s
       282           0.0040           41.71s
       283           0.0039           41.37s
       284           0.0039           40.91s
       285           0.0039           40.51s
       286           0.0039           40.08s
       287           0.0039           39.68s
       288           0.0039           39.26s
       289           0.0039           38.83s
       290           0.0039           38.53s
       291           0.0039           38.07s
       292           0.0039           37.66s
       293           0.0039           37.22s
       294           0.0039           36.80s
       295           0.0039           36.34s
       296           0.0039           35.87s
       297           0.0038           35.41s
       298           0.0038           34.95s
       299           0.0038           34.49s
       300           0.0038           34.03s
       301           0.0038           33.57s
       302           0.0038           33.16s
       303           0.0038           32.77s
       304           0.0038           32.37s
       305           0.0038           31.93s
       306           0.0038           31.61s
       307           0.0038           31.17s
       308           0.0037           30.73s
       309           0.0037           30.29s
       310           0.0037           29.86s
       311           0.0037           29.43s
       312           0.0037           28.98s
       313           0.0037           28.54s
       314           0.0037           28.14s
       315           0.0037           27.78s
       316           0.0037           27.49s
       317           0.0037           27.10s
       318           0.0037           26.66s
       319           0.0037           26.27s
       320           0.0037           25.83s
       321           0.0037           25.48s
       322           0.0036           25.12s
       323           0.0036           24.70s
       324           0.0036           24.32s
       325           0.0036           23.89s
       326           0.0036           23.45s
       327           0.0036           23.00s
       328           0.0036           22.56s
       329           0.0036           22.16s
       330           0.0035           21.71s
       331           0.0035           21.28s
       332           0.0035           20.83s
       333           0.0035           20.38s
       334           0.0035           20.00s
       335           0.0035           19.56s
       336           0.0035           19.14s
       337           0.0035           18.71s
       338           0.0035           18.29s
       339           0.0035           17.83s
       340           0.0035           17.40s
       341           0.0035           16.95s
       342           0.0035           16.51s
       343           0.0035           16.06s
       344           0.0035           15.64s
       345           0.0035           15.23s
       346           0.0034           14.82s
       347           0.0034           14.37s
       348           0.0034           13.93s
       349           0.0034           13.49s
       350           0.0034           13.04s
       351           0.0034           12.60s
       352           0.0034           12.16s
       353           0.0034           11.72s
       354           0.0034           11.28s
       355           0.0034           10.84s
       356           0.0034           10.41s
       357           0.0034            9.97s
       358           0.0034            9.53s
       359           0.0034            9.09s
       360           0.0034            8.65s
       361           0.0034            8.22s
       362           0.0034            7.78s
       363           0.0034            7.34s
       364           0.0034            6.91s
       365           0.0034            6.47s

       366           0.0034            6.04s
       367           0.0034            5.60s
       368           0.0034            5.18s
       369           0.0034            4.74s
       370           0.0034            4.31s
       371           0.0034            3.88s
       372           0.0033            3.44s
       373           0.0033            3.01s
       374           0.0033            2.59s
       375           0.0033            2.16s
       376           0.0033            1.73s
       377           0.0033            1.30s
       378           0.0033            0.86s
       379           0.0033            0.43s
       380           0.0033            0.00s

In [205]:
y_pred = y_pred1*0.15 + y_pred2*0.50 + y_pred3*0.15 + y_pred4*0.20

In [206]:
y_pred = np.exp(y_pred)

In [207]:
y_pred[:5]

array([14406.06843791,  4209.53341524, 12895.31525683, 11535.5327643 ,
        3943.37074688])

In [208]:
df_sub = pd.DataFrame(data=y_pred, columns=['Price'])
writer = pd.ExcelWriter('Output.xlsx', engine='xlsxwriter')
df_sub.to_excel(writer,sheet_name='Sheet1', index=False)
writer.save()